with open('c:/SIAC/templates/configuracion.html', 'r', encoding='utf-8') as f:
    lines = f.readlines()

# Line 2540 (0-indexed 2539) has the mangled content - fix it with proper newlines
good_replacement = [
    '                }\n',
    '            } catch (e) {\n',
    '                alert("Error de conexion al guardar configuracion global.");\n',
    '            }\n',
    '        }\n',
    '\n',
    '        // Per-institution AI config\n',
    '        function updateInstAiModel() {\n',
    "            const provider = document.getElementById('instAiProvider').value;\n",
    "            const modelInput = document.getElementById('instAiModel');\n",
    "            const defaults = { zhipu: 'glm-4', openai: 'gpt-4o-mini', gemini: 'gemini-2.5-flash', anthropic: 'claude-3-5-sonnet-20240620' };\n",
    "            modelInput.value = defaults[provider] || '';\n",
    '        }\n',
    '\n',
    '        async function loadInstAiSettings() {\n',
    '            const instId = getInstId();\n',
    '            if (!instId) return;\n',
    '            try {\n',
    '                const res = await fetch(`/api/inst-ai-settings?inst_id=${instId}&t=` + Date.now());\n',
    '                const data = await res.json();\n',
    "                const statusEl = document.getElementById('instAiStatus');\n",
    '                if (data.has_api_key) {\n',
    "                    statusEl.innerHTML = '<strong>Configuracion propia activa</strong> &mdash; Tu institucion esta usando su propia llave de IA.';\n",
    "                    statusEl.style.background = 'rgba(16,185,129,0.1)';\n",
    "                    statusEl.style.color = '#065f46';\n",
    "                    if (data.ai_provider) document.getElementById('instAiProvider').value = data.ai_provider;\n",
    "                    if (data.ai_model) document.getElementById('instAiModel').value = data.ai_model;\n",
    '                } else {\n',
    "                    statusEl.innerHTML = '<strong>Usando llave global del sistema</strong> &mdash; No has configurado una llave propia aun.';\n",
    "                    statusEl.style.background = 'rgba(99,102,241,0.08)';\n",
    "                    statusEl.style.color = '#3730a3';\n",
    '                }\n',
    "            } catch (e) { console.log('Error loading inst AI settings'); }\n",
    '        }\n',
    '\n',
    '        async function saveInstAiSettings() {\n',
    '            const instId = getInstId();\n',
    '            const payload = {\n',
    '                inst_id: instId,\n',
    "                ai_provider: document.getElementById('instAiProvider').value,\n",
    "                ai_model: document.getElementById('instAiModel').value,\n",
    "                ai_api_key: document.getElementById('instAiKey').value\n",
    '            };\n',
    '            try {\n',
    "                const res = await fetch('/api/inst-ai-settings', { method: 'POST', headers: {'Content-Type':'application/json'}, body: JSON.stringify(payload) });\n",
    '                const data = await res.json();\n',
    "                if (data.status === 'success') {\n",
    "                    alert('Configuracion guardada exitosamente.');\n",
    "                    document.getElementById('instAiKey').value = '';\n",
    '                    loadInstAiSettings();\n',
    "                } else { alert('Error: ' + data.message); }\n",
    "            } catch(e) { alert('Error de conexion.'); }\n",
    '        }\n',
    '\n',
    '        async function clearInstAiSettings() {\n',
    "            if (!confirm('Esto eliminara tu configuracion propia y tu institucion usara la llave global del sistema. Continuar?')) return;\n",
    '            const instId = getInstId();\n',
    '            try {\n',
    "                const res = await fetch('/api/inst-ai-settings', { method: 'POST', headers: {'Content-Type':'application/json'}, body: JSON.stringify({ inst_id: instId, clear_key: true }) });\n",
    '                const data = await res.json();\n',
    "                if (data.status === 'success') { alert('Configuracion propia eliminada. Ahora usas la llave global.'); loadInstAiSettings(); }\n",
    "            } catch(e) { alert('Error de conexion.'); }\n",
    '        }\n',
    '        // End per-institution AI config\n',
    '\n',
    '        async function loadPartners() {\n',
]

# Replace line 2539 (the bad one-liner) with our good replacement
lines[2539] = ''.join(good_replacement)

with open('c:/SIAC/templates/configuracion.html', 'w', encoding='utf-8') as f:
    f.writelines(lines)

print("Done! File fixed.")
